#
# docker build --rm -t derand/ffmpeg .
# docker run -it --rm derand/ffmpeg /bin/sh
#

#FROM        busybox:glibc
FROM        derand/base
MAINTAINER  Andrei Derevyagin

ADD ffmpeg.tar.gz /

CMD ["/bin/sh"]
